# Pandas DataFrames: Creating, Editing, and Cleaning Data

In this lesson, we explored the following pandas topics:

1. **Creating a DataFrame**: Building a DataFrame from raw data with `pd.DataFrame()`.

2. **Editing rows and columns**: Updating existing rows/columns and adding new ones with `.loc[]` and direct column assignment.

3. **Data types**: Inspecting dtypes and converting them with `.astype()`.

4. **Drop**: Deleting rows or columns with `.drop()`.

5. **Rename**: Renaming columns and index labels with `.rename()`.

6. **Replace**: Substituting specific values anywhere in a DataFrame with `.replace()`.

7. **Working with a real dataset**: Loading a messy CSV file and cleaning it up.

    7.1 **Dropping unneeded columns**: Removing columns that aren't needed for the analysis.

    7.2 **Setting a meaningful index**: Using a data column (e.g. `state`) as the index instead of default integers.

    7.3 **Shortening column names**: Renaming columns for convenience.

8. **Converting object columns to numeric**: Fixing mis-typed numeric columns with `pd.to_numeric(..., errors='coerce')`.

9. **Handling missing data**: Detecting, removing, and filling `NaN` values.

    9.1 **Detecting missing values**: By **isna()**

    9.2 **Removing rows with missing values**: By **dropna()**

    9.3 **Filling missing values with a chosen value**: By  **fillna()**

# 1-Creating a DataFrame

In [1]:
import pandas as pd
Data = [[1,7,0],[2,8,3],[3,1,4]]
df = pd.DataFrame(Data,index=['A','B','C'],columns=['x1','x2','x3'])            
#print(df.dtypes)
df

   x1  x2  x3
A   1   7   0
B   2   8   3
C   3   1   4

# 2-Editing rows and columns:

Assign a new list of values to `df.loc[row_label]` to overwrite every value in that row. The list must match the number of columns, in column order.

In [2]:
df.loc['A']=[1,1,20]
df

   x1  x2  x3
A   1   1  20
B   2   8   3
C   3   1   4

Updating an Entire Column:

Assign a new list of values directly to `df['column_name']` to overwrite every value in that column. The list must match the number of rows.

In [3]:
df['x3']=[13,17,9]
#df.loc[:,'x3']=[13,17,9]
df

   x1  x2  x3
A   1   1  13
B   2   8  17
C   3   1   9

`.loc[:, col] = ...` vs. `df[col] = ...`

Both statements look equivalent, but they don't always behave the same way. Direct column assignment (`df['x3'] = [...]`) replaces the column outright, while `.loc[:, 'x3'] = [...]` writes into the existing column in place and is more sensitive to shape or dtype mismatches, which is why it can raise an error where the direct assignment doesn't. When the goal is simply to replace all of a column's values, `df['column'] = [...]` is the safer choice.

In [4]:
df.loc['A','x2']=[1]
df

   x1  x2  x3
A   1   1  13
B   2   8  17
C   3   1   9

In [5]:
df.loc[['B','C'],['x1','x2']]=[[2,2],[30000,3]]                       #or df.loc[['B','C']['x1','x2']] = 1
df

      x1  x2  x3
A      1   1  13
B      2   2  17
C  30000   3   9

**Adding a New Column**

Assigning to a column name that doesn't exist yet creates it: `df['new_col'] = [...]`.

In [6]:
df['x4']=[11,12,13]
df

      x1  x2  x3  x4
A      1   1  13  11
B      2   2  17  12
C  30000   3   9  13

**Adding a New Row**

Assigning to a row label that doesn't exist yet creates it: `df.loc['new_row'] = [...]`.

In [7]:
df.loc['D']=[400,4,63,17]
df.loc['E']=[5,5,27,11]
df.loc['F']=[6000,6,40,13]
df

      x1  x2  x3  x4
A      1   1  13  11
B      2   2  17  12
C  30000   3   9  13
D    400   4  63  17
E      5   5  27  11
F   6000   6  40  13

# 3-Data types

A couple of commands worth remembering when exploring a DataFrame.

In [8]:
df.dtypes

x1    int64
x2    int64
x3    int64
x4    int64
dtype: object

In [9]:
df['x4']

A    11
B    12
C    13
D    17
E    11
F    13
Name: x4, dtype: int64

**Changing Column Data Types**

Use `.astype('type')` to convert data. Note that `df.astype('float')` on its own returns a **new** DataFrame and does not modify `df` in place; to permanently change a single column, reassign it: `df['col'] = df['col'].astype('float')`.

In [10]:
df.astype('float')    # returns a new float DataFrame, but doesn't change df in place
df['x4'] = df['x4'].astype('float')   # this permanently converts the x4 column
df

      x1  x2  x3    x4
A      1   1  13  11.0
B      2   2  17  12.0
C  30000   3   9  13.0
D    400   4  63  17.0
E      5   5  27  11.0
F   6000   6  40  13.0

# 4-Dropping Rows and Columns
The `.drop()` method removes rows or columns. Always pass `inplace=True` (or reassign the result) — otherwise the original DataFrame is left unchanged.

**Dropping Columns**

In [11]:
df.drop(columns=['x1'], inplace=True)   # use inplace=True rather than reassigning to a new variable
df   # x1 was treated as an outlier column, so we removed it from the dataset

   x2  x3    x4
A   1  13  11.0
B   2  17  12.0
C   3   9  13.0
D   4  63  17.0
E   5  27  11.0
F   6  40  13.0

**Dropping Rows**

In [12]:
df.drop(index=['A'], inplace=True)
df

   x2  x3    x4
B   2  17  12.0
C   3   9  13.0
D   4  63  17.0
E   5  27  11.0
F   6  40  13.0

# 5-Rename
**Renaming Columns**

Use `.rename(columns={...})` with a dictionary that maps old names to new names.

In [13]:
df.rename(columns={'x2':'id','x3':'age','x4':'Blood pressure'},inplace=True)   # by dict
df

   id  age  Blood pressure
B   2   17            12.0
C   3    9            13.0
D   4   63            17.0
E   5   27            11.0
F   6   40            13.0

**Renaming Row Labels (Index)**

Use `.rename(index={...})` the same way to relabel rows.

In [14]:
df.rename(index={'B':'Man','D':'Man','F':'Man','C':'Woman','E':'Woman'}, inplace=True)
df

       id  age  Blood pressure
Man     2   17            12.0
Woman   3    9            13.0
Man     4   63            17.0
Woman   5   27            11.0
Man     6   40            13.0

# 6-Replacing Values
`.replace()` lets you substitute specific values anywhere in the DataFrame, in a single column, or in a single cell.

In [15]:
#way_1
df.replace({'age':{9:20}},inplace=True) #change item in the columns that you pass to code
df

       id  age  Blood pressure
Man     2   17            12.0
Woman   3   20            13.0
Man     4   63            17.0
Woman   5   27            11.0
Man     6   40            13.0

In [16]:
#way_2
df.replace({17:30}, inplace=True)  # replace every occurrence of 17 with 30, anywhere in the DataFrame
df

       id  age  Blood pressure
Man     2   30            12.0
Woman   3   20            13.0
Man     4   63            30.0
Woman   5   27            11.0
Man     6   40            13.0

In [17]:
#way_3
#df['x'].replace({0:2},inplace=True)

## 7-Working with a Real, Messy Dataset
From here on, we load a CSV file that has some formatting issues and missing values, and clean it up in this lesson and future step by step.

In [37]:
df_co = pd.read_csv('covid-merged.csv')   # the real header is on row 1, not row 0
df_co

    Unnamed: 0             new     700           ?        ?.1    ?.2
0            0           state   cases  population        gdp  urban
1            1         Alabama    7068     4903185   230750.1  59.04
2            2          Alaska       ?      731545    54674.7  66.02
3            3         Arizona    7648     7278717   379018.8  89.81
4            4        Arkansas    3281     3017804   132596.4  56.16
5            5      California   50470    39512223  3205000.1  94.95
6            6        Colorado   15207     5758736   400863.4  86.15
7            7     Connecticut   27700     3565287     290703  87.99
8            8        Delaware    4734      973764    77879.4      ?
9            9         Florida   33683    21477737  1126510.3  91.16
10          10         Georgia   25431    10617423   634137.5  75.07
11          11          Hawaii     609     1415872    97001.1  91.93
12          12           Idaho    2016     1787065    85791.1  70.58
13          13        Illinois   52918    12671821   893355.5  88.49
14          14         Indiana   18099     6732219   384871.7  72.44
15          15            Iowa    7145     3155070   196247.4  64.02
16          16          Kansas    4305     2913314   178605.1      ?
17          17        Kentucky    4708     4467673   218426.1  58.38
18          18       Louisiana   28044     4648794   259079.3  73.19
19          19           Maine    1095     1344212    68984.9  38.66
20          20        Maryland   21825     6045680   432997.8   87.2
21          21   Massachusetts   62205     6892503   603209.6  91.97
22          22        Michigan   41348     9986857   543489.4  74.57
23          23       Minnesota    5136     5639632   389503.7  73.27
24          24     Mississippi    6815     2976149   117642.3  49.35
25          25        Missouri    7563     6137428   332659.7  70.44
26          26         Montana     452     1068778    54034.7  55.89
27          27        Nebraska    4332     1934408     133201  73.13
28          28          Nevada    5053     3080156   181751.6   94.2
29          29   New Hampshire    2146     1359711    88014.8   60.3
30          30      New Jersey  118652     8882190   642967.7  94.68
31          31      New Mexico    3411     2096829   106914.4  77.43
32          32        New York  309696    19453561  1791566.8  87.87
33          33  North Carolina   10507    10488084   601787.9  66.09
34          34    North Dakota    1067      762062    57471.9   59.9
35          35            Ohio   18027    11689100   703368.9  77.92
36          36        Oklahoma    3618     3956971   201604.3  66.24
37          37          Oregon    2510     4217737   258692.6  81.03
38          38    Pennsylvania   48224           ?   818448.6      ?
39          39    Rhode Island    8621     1059361    62335.4  90.73
40          40  South Carolina    6095     5148714   251664.5  66.33
41          41    South Dakota    2450      884659    56051.9  56.65
42          42       Tennessee   10506     6829174     380823  66.39
43          43           Texas   29072    28995881  1861581.9   84.7
44          44            Utah    4672     3205958   196639.4  90.58
45          45         Vermont       ?      623989    34320.2   38.9
46          46        Virginia   15848     8535519   566529.4  75.45
47          47      Washington   14814     7614893   624861.4  84.05
48          48   West Virginia    1126     1792147    78480.5  48.72
49          49       Wisconsin    6973     5822434   353935.5  70.15
50          50         Wyoming     559      578759    40764.3  64.76

In [38]:
df_co = pd.read_csv('covid-merged.csv', header=1)   # header=1 skips the malformed first row
df_co

     0           state   cases population        gdp  urban
0    1         Alabama    7068    4903185   230750.1  59.04
1    2          Alaska       ?     731545    54674.7  66.02
2    3         Arizona    7648    7278717   379018.8  89.81
3    4        Arkansas    3281    3017804   132596.4  56.16
4    5      California   50470   39512223  3205000.1  94.95
5    6        Colorado   15207    5758736   400863.4  86.15
6    7     Connecticut   27700    3565287   290703.0  87.99
7    8        Delaware    4734     973764    77879.4      ?
8    9         Florida   33683   21477737  1126510.3  91.16
9   10         Georgia   25431   10617423   634137.5  75.07
10  11          Hawaii     609    1415872    97001.1  91.93
11  12           Idaho    2016    1787065    85791.1  70.58
12  13        Illinois   52918   12671821   893355.5  88.49
13  14         Indiana   18099    6732219   384871.7  72.44
14  15            Iowa    7145    3155070   196247.4  64.02
15  16          Kansas    4305    2913314   178605.1      ?
16  17        Kentucky    4708    4467673   218426.1  58.38
17  18       Louisiana   28044    4648794   259079.3  73.19
18  19           Maine    1095    1344212    68984.9  38.66
19  20        Maryland   21825    6045680   432997.8   87.2
20  21   Massachusetts   62205    6892503   603209.6  91.97
21  22        Michigan   41348    9986857   543489.4  74.57
22  23       Minnesota    5136    5639632   389503.7  73.27
23  24     Mississippi    6815    2976149   117642.3  49.35
24  25        Missouri    7563    6137428   332659.7  70.44
25  26         Montana     452    1068778    54034.7  55.89
26  27        Nebraska    4332    1934408   133201.0  73.13
27  28          Nevada    5053    3080156   181751.6   94.2
28  29   New Hampshire    2146    1359711    88014.8   60.3
29  30      New Jersey  118652    8882190   642967.7  94.68
30  31      New Mexico    3411    2096829   106914.4  77.43
31  32        New York  309696   19453561  1791566.8  87.87
32  33  North Carolina   10507   10488084   601787.9  66.09
33  34    North Dakota    1067     762062    57471.9   59.9
34  35            Ohio   18027   11689100   703368.9  77.92
35  36        Oklahoma    3618    3956971   201604.3  66.24
36  37          Oregon    2510    4217737   258692.6  81.03
37  38    Pennsylvania   48224          ?   818448.6      ?
38  39    Rhode Island    8621    1059361    62335.4  90.73
39  40  South Carolina    6095    5148714   251664.5  66.33
40  41    South Dakota    2450     884659    56051.9  56.65
41  42       Tennessee   10506    6829174   380823.0  66.39
42  43           Texas   29072   28995881  1861581.9   84.7
43  44            Utah    4672    3205958   196639.4  90.58
44  45         Vermont       ?     623989    34320.2   38.9
45  46        Virginia   15848    8535519   566529.4  75.45
46  47      Washington   14814    7614893   624861.4  84.05
47  48   West Virginia    1126    1792147    78480.5  48.72
48  49       Wisconsin    6973    5822434   353935.5  70.15
49  50         Wyoming     559     578759    40764.3  64.76

In [39]:
df_co.head()

   0       state  cases population        gdp  urban
0  1     Alabama   7068    4903185   230750.1  59.04
1  2      Alaska      ?     731545    54674.7  66.02
2  3     Arizona   7648    7278717   379018.8  89.81
3  4    Arkansas   3281    3017804   132596.4  56.16
4  5  California  50470   39512223  3205000.1  94.95

**7.1-Dropping Unneeded Columns**

Remove the unnamed index column (`'0'`) and the `'urban'` column, which aren't needed for this analysis.

In [40]:
df_co.drop(columns={'0','urban'},inplace=True)
df_co

             state   cases population        gdp
0          Alabama    7068    4903185   230750.1
1           Alaska       ?     731545    54674.7
2          Arizona    7648    7278717   379018.8
3         Arkansas    3281    3017804   132596.4
4       California   50470   39512223  3205000.1
5         Colorado   15207    5758736   400863.4
6      Connecticut   27700    3565287   290703.0
7         Delaware    4734     973764    77879.4
8          Florida   33683   21477737  1126510.3
9          Georgia   25431   10617423   634137.5
10          Hawaii     609    1415872    97001.1
11           Idaho    2016    1787065    85791.1
12        Illinois   52918   12671821   893355.5
13         Indiana   18099    6732219   384871.7
14            Iowa    7145    3155070   196247.4
15          Kansas    4305    2913314   178605.1
16        Kentucky    4708    4467673   218426.1
17       Louisiana   28044    4648794   259079.3
18           Maine    1095    1344212    68984.9
19        Maryland   21825    6045680   432997.8
20   Massachusetts   62205    6892503   603209.6
21        Michigan   41348    9986857   543489.4
22       Minnesota    5136    5639632   389503.7
23     Mississippi    6815    2976149   117642.3
24        Missouri    7563    6137428   332659.7
25         Montana     452    1068778    54034.7
26        Nebraska    4332    1934408   133201.0
27          Nevada    5053    3080156   181751.6
28   New Hampshire    2146    1359711    88014.8
29      New Jersey  118652    8882190   642967.7
30      New Mexico    3411    2096829   106914.4
31        New York  309696   19453561  1791566.8
32  North Carolina   10507   10488084   601787.9
33    North Dakota    1067     762062    57471.9
34            Ohio   18027   11689100   703368.9
35        Oklahoma    3618    3956971   201604.3
36          Oregon    2510    4217737   258692.6
37    Pennsylvania   48224          ?   818448.6
38    Rhode Island    8621    1059361    62335.4
39  South Carolina    6095    5148714   251664.5
40    South Dakota    2450     884659    56051.9
41       Tennessee   10506    6829174   380823.0
42           Texas   29072   28995881  1861581.9
43            Utah    4672    3205958   196639.4
44         Vermont       ?     623989    34320.2
45        Virginia   15848    8535519   566529.4
46      Washington   14814    7614893   624861.4
47   West Virginia    1126    1792147    78480.5
48       Wisconsin    6973    5822434   353935.5
49         Wyoming     559     578759    40764.3

**7.2-Setting a meaningful index**

Replace the default numeric index with the `'state'` column so each row is labeled by state name.

In [41]:
df_co.rename(index=df_co['state'],inplace=True)
df_co

                         state   cases population        gdp
Alabama                Alabama    7068    4903185   230750.1
Alaska                  Alaska       ?     731545    54674.7
Arizona                Arizona    7648    7278717   379018.8
Arkansas              Arkansas    3281    3017804   132596.4
California          California   50470   39512223  3205000.1
Colorado              Colorado   15207    5758736   400863.4
Connecticut        Connecticut   27700    3565287   290703.0
Delaware              Delaware    4734     973764    77879.4
Florida                Florida   33683   21477737  1126510.3
Georgia                Georgia   25431   10617423   634137.5
Hawaii                  Hawaii     609    1415872    97001.1
Idaho                    Idaho    2016    1787065    85791.1
Illinois              Illinois   52918   12671821   893355.5
Indiana                Indiana   18099    6732219   384871.7
Iowa                      Iowa    7145    3155070   196247.4
Kansas                  Kansas    4305    2913314   178605.1
Kentucky              Kentucky    4708    4467673   218426.1
Louisiana            Louisiana   28044    4648794   259079.3
Maine                    Maine    1095    1344212    68984.9
Maryland              Maryland   21825    6045680   432997.8
Massachusetts    Massachusetts   62205    6892503   603209.6
Michigan              Michigan   41348    9986857   543489.4
Minnesota            Minnesota    5136    5639632   389503.7
Mississippi        Mississippi    6815    2976149   117642.3
Missouri              Missouri    7563    6137428   332659.7
Montana                Montana     452    1068778    54034.7
Nebraska              Nebraska    4332    1934408   133201.0
Nevada                  Nevada    5053    3080156   181751.6
New Hampshire    New Hampshire    2146    1359711    88014.8
New Jersey          New Jersey  118652    8882190   642967.7
New Mexico          New Mexico    3411    2096829   106914.4
New York              New York  309696   19453561  1791566.8
North Carolina  North Carolina   10507   10488084   601787.9
North Dakota      North Dakota    1067     762062    57471.9
Ohio                      Ohio   18027   11689100   703368.9
Oklahoma              Oklahoma    3618    3956971   201604.3
Oregon                  Oregon    2510    4217737   258692.6
Pennsylvania      Pennsylvania   48224          ?   818448.6
Rhode Island      Rhode Island    8621    1059361    62335.4
South Carolina  South Carolina    6095    5148714   251664.5
South Dakota      South Dakota    2450     884659    56051.9
Tennessee            Tennessee   10506    6829174   380823.0
Texas                    Texas   29072   28995881  1861581.9
Utah                      Utah    4672    3205958   196639.4
Vermont                Vermont       ?     623989    34320.2
Virginia              Virginia   15848    8535519   566529.4
Washington          Washington   14814    7614893   624861.4
West Virginia    West Virginia    1126    1792147    78480.5
Wisconsin            Wisconsin    6973    5822434   353935.5
Wyoming                Wyoming     559     578759    40764.3

**Dropping the Original 'state' Column**

Now that its values are being used as the index, the original `'state'` column can be dropped.

In [42]:
df_co.drop(columns={'state'},inplace=True)
df_co

                 cases population        gdp
Alabama           7068    4903185   230750.1
Alaska               ?     731545    54674.7
Arizona           7648    7278717   379018.8
Arkansas          3281    3017804   132596.4
California       50470   39512223  3205000.1
Colorado         15207    5758736   400863.4
Connecticut      27700    3565287   290703.0
Delaware          4734     973764    77879.4
Florida          33683   21477737  1126510.3
Georgia          25431   10617423   634137.5
Hawaii             609    1415872    97001.1
Idaho             2016    1787065    85791.1
Illinois         52918   12671821   893355.5
Indiana          18099    6732219   384871.7
Iowa              7145    3155070   196247.4
Kansas            4305    2913314   178605.1
Kentucky          4708    4467673   218426.1
Louisiana        28044    4648794   259079.3
Maine             1095    1344212    68984.9
Maryland         21825    6045680   432997.8
Massachusetts    62205    6892503   603209.6
Michigan         41348    9986857   543489.4
Minnesota         5136    5639632   389503.7
Mississippi       6815    2976149   117642.3
Missouri          7563    6137428   332659.7
Montana            452    1068778    54034.7
Nebraska          4332    1934408   133201.0
Nevada            5053    3080156   181751.6
New Hampshire     2146    1359711    88014.8
New Jersey      118652    8882190   642967.7
New Mexico        3411    2096829   106914.4
New York        309696   19453561  1791566.8
North Carolina   10507   10488084   601787.9
North Dakota      1067     762062    57471.9
Ohio             18027   11689100   703368.9
Oklahoma          3618    3956971   201604.3
Oregon            2510    4217737   258692.6
Pennsylvania     48224          ?   818448.6
Rhode Island      8621    1059361    62335.4
South Carolina    6095    5148714   251664.5
South Dakota      2450     884659    56051.9
Tennessee        10506    6829174   380823.0
Texas            29072   28995881  1861581.9
Utah              4672    3205958   196639.4
Vermont              ?     623989    34320.2
Virginia         15848    8535519   566529.4
Washington       14814    7614893   624861.4
West Virginia     1126    1792147    78480.5
Wisconsin         6973    5822434   353935.5
Wyoming            559     578759    40764.3

**7.3-Shortening Column Names**

Rename the columns to shorter, more convenient labels.

In [43]:
df_co.rename(columns={'Cases':'ca','population':'pop','gdp':'g'},inplace=True)
df_co

                 cases       pop          g
Alabama           7068   4903185   230750.1
Alaska               ?    731545    54674.7
Arizona           7648   7278717   379018.8
Arkansas          3281   3017804   132596.4
California       50470  39512223  3205000.1
Colorado         15207   5758736   400863.4
Connecticut      27700   3565287   290703.0
Delaware          4734    973764    77879.4
Florida          33683  21477737  1126510.3
Georgia          25431  10617423   634137.5
Hawaii             609   1415872    97001.1
Idaho             2016   1787065    85791.1
Illinois         52918  12671821   893355.5
Indiana          18099   6732219   384871.7
Iowa              7145   3155070   196247.4
Kansas            4305   2913314   178605.1
Kentucky          4708   4467673   218426.1
Louisiana        28044   4648794   259079.3
Maine             1095   1344212    68984.9
Maryland         21825   6045680   432997.8
Massachusetts    62205   6892503   603209.6
Michigan         41348   9986857   543489.4
Minnesota         5136   5639632   389503.7
Mississippi       6815   2976149   117642.3
Missouri          7563   6137428   332659.7
Montana            452   1068778    54034.7
Nebraska          4332   1934408   133201.0
Nevada            5053   3080156   181751.6
New Hampshire     2146   1359711    88014.8
New Jersey      118652   8882190   642967.7
New Mexico        3411   2096829   106914.4
New York        309696  19453561  1791566.8
North Carolina   10507  10488084   601787.9
North Dakota      1067    762062    57471.9
Ohio             18027  11689100   703368.9
Oklahoma          3618   3956971   201604.3
Oregon            2510   4217737   258692.6
Pennsylvania     48224         ?   818448.6
Rhode Island      8621   1059361    62335.4
South Carolina    6095   5148714   251664.5
South Dakota      2450    884659    56051.9
Tennessee        10506   6829174   380823.0
Texas            29072  28995881  1861581.9
Utah              4672   3205958   196639.4
Vermont              ?    623989    34320.2
Virginia         15848   8535519   566529.4
Washington       14814   7614893   624861.4
West Virginia     1126   1792147    78480.5
Wisconsin         6973   5822434   353935.5
Wyoming            559    578759    40764.3

# 8-Converting Object Columns to Numeric

**Why This Matters**

Columns imported from a CSV are sometimes read as `object` (text) even when they contain numbers, usually because of stray characters or inconsistent formatting. Numeric columns should always be converted to a proper numeric dtype before doing any calculations. `pd.to_numeric()` handles this conversion, and the `errors='coerce'` argument turns any value that can't be parsed into `NaN` instead of raising an error.

In [44]:
df_co.info()

<class 'pandas.DataFrame'>
Index: 50 entries, Alabama to Wyoming
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   cases   50 non-null     str
 1   pop     50 non-null     str
 2   g       50 non-null     float64
dtypes: float64(1), str(2)
memory usage: 1.6+ KB

In [45]:
# if we see number in data and type of them is object we can this way pd.to_numeric(df_co['cases'],errors='coerce')

In [46]:
?pd.to_numeric

Signature:
pd.to_numeric(
    arg,
    errors: 'DateTimeErrorChoices' = 'raise',
    downcast: "Literal['integer', 'signed', 'unsigned', 'float'] | None" = None,
    dtype_backend: 'DtypeBackend | lib.NoDefault' = <no_default>,
)
Docstring:
Convert argument to a numeric type.

If the input is already of a numeric dtype, the dtype will be preserved.
For non-numeric inputs, the default return dtype is `float64` or `int64`
depending on the data supplied. Use the `downcast` parameter
to obtain other dtypes.

Please note that precision loss may occur if really large numbers
are passed in. Due to the internal limitations of `ndarray`, if
numbers smaller than `-9223372036854775808` (np.iinfo(np.int64).min)
or larger than `18446744073709551615` (np.iinfo(np.uint64).max) are
passed in, it is very likely they will be converted to float so that
they can be stored in an `ndarray`. These warnings apply similarly to
`Series` since it internally leverages `ndarray`.

Parameters
----------
arg : scalar, list, tuple, 1-d array, or Series
    Argument to be converted.

errors : {'raise', 'coerce'}, default 'raise'
    - If 'raise', then invalid parsing will raise an exception.
    - If 'coerce', then invalid parsing will be set as NaN.

downcast : str, default None
    Can be 'integer', 'signed', 'unsigned', or 'float'.
    If not None, and if the data has been successfully cast to a
    numerical dtype (or if the data was numeric to begin with),
    downcast that resulting data to the smallest numerical dtype
    possible according to the following rules:

    - 'integer' or 'signed': smallest signed int dtype (min.: np.int8)
    - 'unsigned': smallest unsigned int dtype (min.: np.uint8)
    - 'float': smallest float dtype (min.: np.float32)

    As this behaviour is separate from the core conversion to
    numeric values, any errors raised during the downcasting
    will be surfaced regardless of the value of the 'errors' input.

    In addition, downcasting will only occur if the size
    of the resulting data's dtype is strictly larger than
    the dtype it is to be cast to, so if none of the dtypes
    checked satisfy that specification, no downcasting will be
    performed on the data.

dtype_backend : {'numpy_nullable', 'pyarrow'}
    Back-end data type applied to the resultant :class:`DataFrame`
    (still experimental). If not specified, the default behavior
    is to not use nullable data types. If specified, the behavior
    is as follows:

    * ``"numpy_nullable"``: returns nullable-dtype-backed object
    * ``"pyarrow"``: returns with pyarrow-backed nullable object

    .. versionadded:: 2.0

Returns
-------
ret
    Numeric if parsing succeeded.
    Return type depends on input.  Series if Series, otherwise ndarray.

Raises
------
ValueError
    If the input contains non-numeric values and `errors='raise'`.
TypeError
    If the input is not list-like, 1D, or scalar convertible to numeric,
    such as nested lists or unsupported input types (e.g., dict).

See Also
--------
DataFrame.astype : Cast argument to a specified dtype.
to_datetime : Convert argument to datetime.
to_timedelta : Convert argument to timedelta.
numpy.ndarray.astype : Cast a numpy array to a specified type.
DataFrame.convert_dtypes : Convert dtypes.

Examples
--------
Take separate series and convert to numeric, coercing when told to

>>> s = pd.Series(["1.0", "2", -3])
>>> pd.to_numeric(s)
0    1.0
1    2.0
2   -3.0
dtype: float64
>>> pd.to_numeric(s, downcast="float")
0    1.0
1    2.0
2   -3.0
dtype: float32
>>> pd.to_numeric(s, downcast="signed")
0    1
1    2
2   -3
dtype: int8
>>> s = pd.Series(["apple", "1.0", "2", -3])
>>> pd.to_numeric(s, errors="coerce")
0    NaN
1    1.0
2    2.0
3   -3.0
dtype: float64

Downcasting of nullable integer and floating dtypes is supported:

>>> s = pd.Series([1, 2, 3], dtype="Int64")
>>> pd.to_numeric(s, downcast="integer")
0    1
1    2
2    3
dtype: Int8
>>> s = pd.Series([1.0, 2.1, 3.0], dtype="Float64")
>>> pd.to_numeric(s, downcast="float")
0    1.0
1    2.1
2    3.0
dtype: Float32
File:      c:\users\fanavaran\appdata\roaming\python\python311\site-packages\pandas\core\tools\numeric.py
Type:      function

In [47]:
df_co['cases']  = pd.to_numeric(df_co['cases'],errors='coerce')
# note: the dtype is still 'object' at this point because only one column has been converted so far

In [48]:
df_co['cases']  = pd.to_numeric(df_co['cases'],errors='coerce')
df_co['pop'] = pd.to_numeric(df_co['pop'],errors='coerce')
df_co['g']   = pd.to_numeric(df_co['g'],errors='coerce')
df_co

                   cases         pop          g
Alabama           7068.0   4903185.0   230750.1
Alaska               NaN    731545.0    54674.7
Arizona           7648.0   7278717.0   379018.8
Arkansas          3281.0   3017804.0   132596.4
California       50470.0  39512223.0  3205000.1
Colorado         15207.0   5758736.0   400863.4
Connecticut      27700.0   3565287.0   290703.0
Delaware          4734.0    973764.0    77879.4
Florida          33683.0  21477737.0  1126510.3
Georgia          25431.0  10617423.0   634137.5
Hawaii             609.0   1415872.0    97001.1
Idaho             2016.0   1787065.0    85791.1
Illinois         52918.0  12671821.0   893355.5
Indiana          18099.0   6732219.0   384871.7
Iowa              7145.0   3155070.0   196247.4
Kansas            4305.0   2913314.0   178605.1
Kentucky          4708.0   4467673.0   218426.1
Louisiana        28044.0   4648794.0   259079.3
Maine             1095.0   1344212.0    68984.9
Maryland         21825.0   6045680.0   432997.8
Massachusetts    62205.0   6892503.0   603209.6
Michigan         41348.0   9986857.0   543489.4
Minnesota         5136.0   5639632.0   389503.7
Mississippi       6815.0   2976149.0   117642.3
Missouri          7563.0   6137428.0   332659.7
Montana            452.0   1068778.0    54034.7
Nebraska          4332.0   1934408.0   133201.0
Nevada            5053.0   3080156.0   181751.6
New Hampshire     2146.0   1359711.0    88014.8
New Jersey      118652.0   8882190.0   642967.7
New Mexico        3411.0   2096829.0   106914.4
New York        309696.0  19453561.0  1791566.8
North Carolina   10507.0  10488084.0   601787.9
North Dakota      1067.0    762062.0    57471.9
Ohio             18027.0  11689100.0   703368.9
Oklahoma          3618.0   3956971.0   201604.3
Oregon            2510.0   4217737.0   258692.6
Pennsylvania     48224.0         NaN   818448.6
Rhode Island      8621.0   1059361.0    62335.4
South Carolina    6095.0   5148714.0   251664.5
South Dakota      2450.0    884659.0    56051.9
Tennessee        10506.0   6829174.0   380823.0
Texas            29072.0  28995881.0  1861581.9
Utah              4672.0   3205958.0   196639.4
Vermont              NaN    623989.0    34320.2
Virginia         15848.0   8535519.0   566529.4
Washington       14814.0   7614893.0   624861.4
West Virginia     1126.0   1792147.0    78480.5
Wisconsin         6973.0   5822434.0   353935.5
Wyoming            559.0    578759.0    40764.3

# 9-Handling Missing Data

**9.1-Detecting Missing Values**

Use `.isna()` to see a boolean mask of missing values, or `.isna().sum()` to get a per-column count — much more practical on larger datasets.

In [52]:
df_co.isna()            # isn't good when we have a lot of data but another one by .sum() is nececessary.
#or
df_co.isna().sum()

cases    2
pop      1
g        0
dtype: int64

**9.2-Removing Missing Values**

`.dropna()` removes every row that contains at least one `NaN` value.

In [35]:
df_co.dropna(inplace=True)    #remove all row that have NaN value in thier coulmns.
df_co

                   cases         pop          g
Alabama           7068.0   4903185.0   230750.1
Arizona           7648.0   7278717.0   379018.8
Arkansas          3281.0   3017804.0   132596.4
California       50470.0  39512223.0  3205000.1
Colorado         15207.0   5758736.0   400863.4
Connecticut      27700.0   3565287.0   290703.0
Delaware          4734.0    973764.0    77879.4
Florida          33683.0  21477737.0  1126510.3
Georgia          25431.0  10617423.0   634137.5
Hawaii             609.0   1415872.0    97001.1
Idaho             2016.0   1787065.0    85791.1
Illinois         52918.0  12671821.0   893355.5
Indiana          18099.0   6732219.0   384871.7
Iowa              7145.0   3155070.0   196247.4
Kansas            4305.0   2913314.0   178605.1
Kentucky          4708.0   4467673.0   218426.1
Louisiana        28044.0   4648794.0   259079.3
Maine             1095.0   1344212.0    68984.9
Maryland         21825.0   6045680.0   432997.8
Massachusetts    62205.0   6892503.0   603209.6
Michigan         41348.0   9986857.0   543489.4
Minnesota         5136.0   5639632.0   389503.7
Mississippi       6815.0   2976149.0   117642.3
Missouri          7563.0   6137428.0   332659.7
Montana            452.0   1068778.0    54034.7
Nebraska          4332.0   1934408.0   133201.0
Nevada            5053.0   3080156.0   181751.6
New Hampshire     2146.0   1359711.0    88014.8
New Jersey      118652.0   8882190.0   642967.7
New Mexico        3411.0   2096829.0   106914.4
New York        309696.0  19453561.0  1791566.8
North Carolina   10507.0  10488084.0   601787.9
North Dakota      1067.0    762062.0    57471.9
Ohio             18027.0  11689100.0   703368.9
Oklahoma          3618.0   3956971.0   201604.3
Oregon            2510.0   4217737.0   258692.6
Rhode Island      8621.0   1059361.0    62335.4
South Carolina    6095.0   5148714.0   251664.5
South Dakota      2450.0    884659.0    56051.9
Tennessee        10506.0   6829174.0   380823.0
Texas            29072.0  28995881.0  1861581.9
Utah              4672.0   3205958.0   196639.4
Virginia         15848.0   8535519.0   566529.4
Washington       14814.0   7614893.0   624861.4
West Virginia     1126.0   1792147.0    78480.5
Wisconsin         6973.0   5822434.0   353935.5
Wyoming            559.0    578759.0    40764.3

**9.3-Filling Missing Values**

`.fillna()` replaces `NaN` values with a value of your choice — either a single value applied to the whole DataFrame, or a dictionary specifying a different fill value per column.

In [54]:
df_co.fillna(0,inplace=True)    # fill all row that have NaN value by 0 value.
#or
df_co.fillna({'cases':0,'pop':1,'g':-1},inplace=True)  # fill all row that have NaN value by yourselves value.

                   cases         pop          g
Alabama           7068.0   4903185.0   230750.1
Alaska               0.0    731545.0    54674.7
Arizona           7648.0   7278717.0   379018.8
Arkansas          3281.0   3017804.0   132596.4
California       50470.0  39512223.0  3205000.1
Colorado         15207.0   5758736.0   400863.4
Connecticut      27700.0   3565287.0   290703.0
Delaware          4734.0    973764.0    77879.4
Florida          33683.0  21477737.0  1126510.3
Georgia          25431.0  10617423.0   634137.5
Hawaii             609.0   1415872.0    97001.1
Idaho             2016.0   1787065.0    85791.1
Illinois         52918.0  12671821.0   893355.5
Indiana          18099.0   6732219.0   384871.7
Iowa              7145.0   3155070.0   196247.4
Kansas            4305.0   2913314.0   178605.1
Kentucky          4708.0   4467673.0   218426.1
Louisiana        28044.0   4648794.0   259079.3
Maine             1095.0   1344212.0    68984.9
Maryland         21825.0   6045680.0   432997.8
Massachusetts    62205.0   6892503.0   603209.6
Michigan         41348.0   9986857.0   543489.4
Minnesota         5136.0   5639632.0   389503.7
Mississippi       6815.0   2976149.0   117642.3
Missouri          7563.0   6137428.0   332659.7
Montana            452.0   1068778.0    54034.7
Nebraska          4332.0   1934408.0   133201.0
Nevada            5053.0   3080156.0   181751.6
New Hampshire     2146.0   1359711.0    88014.8
New Jersey      118652.0   8882190.0   642967.7
New Mexico        3411.0   2096829.0   106914.4
New York        309696.0  19453561.0  1791566.8
North Carolina   10507.0  10488084.0   601787.9
North Dakota      1067.0    762062.0    57471.9
Ohio             18027.0  11689100.0   703368.9
Oklahoma          3618.0   3956971.0   201604.3
Oregon            2510.0   4217737.0   258692.6
Pennsylvania     48224.0         0.0   818448.6
Rhode Island      8621.0   1059361.0    62335.4
South Carolina    6095.0   5148714.0   251664.5
South Dakota      2450.0    884659.0    56051.9
Tennessee        10506.0   6829174.0   380823.0
Texas            29072.0  28995881.0  1861581.9
Utah              4672.0   3205958.0   196639.4
Vermont              0.0    623989.0    34320.2
Virginia         15848.0   8535519.0   566529.4
Washington       14814.0   7614893.0   624861.4
West Virginia     1126.0   1792147.0    78480.5
Wisconsin         6973.0   5822434.0   353935.5
Wyoming            559.0    578759.0    40764.3